### ISSUE TITLE
Rotation "hiding" buttons. 

### ISSUE THREAD

**Issue by cyberon** [franciscofranco/Focus-bugtracker#10]
When rotating the screen on the main screen we can't interact with the buttons placed on the right like the camera and expand, this is being caused by the navigation bar on my Nexus 6.

**Comment by franciscofranco** [comment]
I just reproduced it. Will fix and close this issue once the fix is live. Thanks.

**Comment by franciscofranco** [comment]
Fixed for Beta 1.2.
