### ISSUE TITLE
BUG - 1.3-beta1 Unable to add any tags at all

### ISSUE THREAD

**Issue by haladam** [franciscofranco/Focus-bugtracker#12]
With the 1.3-beta1 update, it is impossible for me to add any tags to any of the photos, whether some of the preset ones or a custom one. The app freezes for a second after choosing a tag for a photo but nothing happens afterwards.

Samsung Galaxy S7 - Exynos version, running the latest official firmware  (6.0.1), no rooting or xposed funky stuff here.

**Comment by franciscofranco** [comment]
I can't reproduce, also app freezing for a second is weird since I offload that process to a background thread. Can you do a screen record and show me?

**Comment by haladam** [comment]
Here you go: https://drive.google.com/file/d/0BzXAtOEzQdO5cWZES1JYaFNOU2s/view?usp=drivesdk

Hope it helps. After choosing the tag, you can see that something seems to have happened in the top part of the screen but the phone simply stopped reacting to the buttons and the tag wasn't added.

**Comment by haladam** [comment]
Interestingly enough, I am able to add tags in a full screen view of a specific picture. Hope this info somehow helps when trying to fix this.

**Comment by franciscofranco** [comment]
Thanks :)

**Comment by haladam** [comment]
Solved with the latest beta 1607060535.
