### ISSUE TITLE
1.3 Beta 1.  Local Folder Tags Applied to Every Image on SD Card

### ISSUE THREAD

**Issue by danielrrhodes** [franciscofranco/Focus-bugtracker#14]
In main view, all images are sorted by folder tags.  When tag is clicked on, i.e. "Kids", it again shows every folder on the SD card, but each category is just titled with a date, i.e. "Kids" folder is listed as March 2014, "House" folder is listed under April, 2016, etc.  Have tried clearing app data and it opens exactly the same.  Also the same whether the "local folders" sort is selected in settings or not.

**Comment by franciscofranco** [comment]
I have no idea what-so-ever how that can happen. What's your device, android version etc.

**Comment by danielrrhodes** [comment]
Nexus 5, Android 6.0.1, June 1 patch.  If you have a hangout or email
address, I can show you some screen shots

**Comment by danielrrhodes** [comment]
Just updated to today's beta and everything is working properly.  Very odd.
