### ISSUE TITLE
1.3-Beta1 BUG: Videos in Tags are in the wrong places

### ISSUE THREAD

**Issue by taaem** [franciscofranco/Focus-bugtracker#15]
When you tag a video it gets sorted in as usual pictures but always at the bottom of the month.
The bug is that when you tag a video but there are pictures from a month before in the overview it gets shown at the end of the month, but when you click on it it opens the next picture and you can find it by going to the last item of all months. 
So the single image view sorts pictures always before videos but the overview sorts pictures before videos in that month. 

Best regards

**Comment by franciscofranco** [comment]
Yes, I'm aware, will fix soon!

**Comment by taaem** [comment]
Just a heads up, still a problem in Beta 1.2

**Comment by franciscofranco** [comment]
Should be fixed in the next beta.

**Comment by franciscofranco** [comment]
Fixed on beta 2.
