### ISSUE TITLE
1.3-Beta1/Beta1.1 BUG: App crashes on start

### ISSUE THREAD

**Issue by ecbjo** [franciscofranco/Focus-bugtracker#16]
Crash on App start. Gives following exceptions:

AndroidRuntime: Process: com.franco.focus, PID:1477
AndroidRuntime: at com.franco.focus.ThumbnailAdapter.a(SourceFile:234)
AndroidRuntime: at com.franco.focus.ThumbnailAdapter.b(SourceFile:47)

Only happens on Android KitKat 4.4, works fine on Android 5.1. Tried clearing data without success.

**Comment by franciscofranco** [comment]
Yeah, I added in a fix for that on 1.1, but it seems I wasn't successful. Should work in the next version.

**Comment by franciscofranco** [comment]
Fixed on Beta 1.2. Submit another issue if it persists.
