### ISSUE TITLE
Photosphere

### ISSUE THREAD

**Issue by LeonZewe** [franciscofranco/Focus-bugtracker#18]
When opening a photosphere image and closing it again, the "Panorama Viewer" activity that is displaying the image opens over and over again around every 10 seconds, even after closinf Focus with the back button. Killing it in recent apps stops it.

**Comment by LeonZewe** [comment]
Woops, forgot to add some information. Im on the latest Focus beta with a Nexus 6p running Android 6.0.1.

**Comment by franciscofranco** [comment]
I can't reproduce, same phone, same Android version. I'll put in a small workaround, hopefully fixes it for you.

**Comment by franciscofranco** [comment]
I can't reproduce no matter what. I'm sorry.

**Comment by LeonZewe** [comment]
Weird, thanks for the help tho.
