### ISSUE TITLE
App froze deleting a whole folder

### ISSUE THREAD

**Issue by chrisvasqm** [franciscofranco/Focus-bugtracker#19]
I long pressed my WhatsApp folder to delete about 30 pictures and when I clicked on Delete it just froze for about 10 seconds on a Nexus 5X (all stock and no battery saving mode enabled if that matters) but at the end it did finish deleting all the pictures.

**Comment by LeonZewe** [comment]
Same here, I think its related to the amount of images it has to delete.

**Comment by franciscofranco** [comment]
Ok, that's not fun. I'll double check if I have that offloaded to a background thread.

How many pictures are we talking about here (just for reference)?

**Comment by chrisvasqm** [comment]
Around 30-40 pictures I would say.

**Comment by franciscofranco** [comment]
Thanks, I'll try to reproduce.

**Comment by franciscofranco** [comment]
I put in a fix for the best update, should help - a part of the job wasn't running in a background thread, but it will now.

**Comment by chrisvasqm** [comment]
Much love 😘

**Comment by franciscofranco** [comment]
Coming up for Beta1.2. Submit another ticket if it happens again please.
