### ISSUE TITLE
Photos not showing on tablet (Nexus 7 2013)

### ISSUE THREAD

**Issue by JovieBrett** [franciscofranco/Focus-bugtracker#24]
I just installed Focus beta v1.3 on my Nexus 7 2013, 6.0.1 and photos doesn't show up even if I allowed permission to use storage. 
Also the tile name of the app is unaligned.

http://i.imgur.com/1kac02x.jpg
http://i.imgur.com/hP6S0h0.jpg

**Comment by franciscofranco** [comment]
Yeah, there's a bug on the tablet layout, will be fixed in the next beta.

**Comment by franciscofranco** [comment]
Fixed on beta 2.
