### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by amemkdm** [franciscofranco/Focus-bugtracker#26]
When i delete a photo from vault the photo is not getting deleted and when i leave vault the app crashes.

**Comment by amemkdm** [comment]
Also now i just unhide two photos from vault and they both disappeared.

**Comment by amemkdm** [comment]
Only the vault is having problems. I am not able to unhide photos. They disappear. Can i know where they are stored so i can manually recover them?

**Comment by franciscofranco** [comment]
When you un-vault a picture it goes to /sdcard/Pictures/

**Comment by amemkdm** [comment]
Thank you very much. By the way why it is not showing images from pictures folder? Is it android N issue? Whenever i change a location of a file my phone is not detecting them. Its happening with music files also.

**Comment by franciscofranco** [comment]
Most likely Android N's issue...
