### ISSUE TITLE
Muzei can't get pictures after a reboot

### ISSUE THREAD

**Issue by taaem** [franciscofranco/Focus-bugtracker#27]
After a reboot you start with a black Wallpaper, after you open Focus and wait until it loads all tags you can go into the Muzei app and go a picture forward and it will load normally.
Happens after every reboot for me on latest Beta.

**Comment by franciscofranco** [comment]
Nice catch!

**Comment by franciscofranco** [comment]
Should be ok with the new beta 2. Start a new issue if it's not fixed for you.
