### ISSUE TITLE
Photo lock

### ISSUE THREAD

**Issue by amemkdm** [franciscofranco/Focus-bugtracker#8]
When i lock a particular photo i am not able to unlock that photo with fingerprint, i have to use the code to unlock it.

**Comment by franciscofranco** [comment]
I just reproduced it. Will fix and close this issue once the fix is live. Thanks.

**Comment by franciscofranco** [comment]
Fixed on my local build, will be available on the next release.

**Comment by franciscofranco** [comment]
Fixed on Beta1.1.
