### ISSUE TITLE
thumbnails do not correspond to the images

### ISSUE THREAD

**Issue by jacopodg** [franciscofranco/Focus-bugtracker#9]
The videos in folders (not collected in a folder), when pressed does not open the video preview, but it opens the next photo, so consequently all the images are not corresponding to the preview, videos are all in the bottom of the folder

**Comment by franciscofranco** [comment]
With the "Group videos" setting disabled?

**Comment by jacopodg** [comment]
Yes

**Comment by franciscofranco** [comment]
I just reproduced it, nice catch. Will close this issue when the fix goes live.

**Comment by jacopodg** [comment]
OK thanks

**Comment by franciscofranco** [comment]
Should be fixed in the next beta.

**Comment by jacopodg** [comment]
thank you

**Comment by franciscofranco** [comment]
Fixed on beta 2.
